name: CI DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies for frontend
        working-directory: ./app/frontend
        run: npm install
      
      - name: Install dependencies for backend
        working-directory: ./app/backend
        run: npm install

      - name: Run unit tests for frontend
        working-directory: ./app/frontend
        run: npm test

      - name: Run unit tests for backend
        working-directory: ./app/backend
        run: npm test

      - name: SonarQube Scan for frontend
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: ./app/frontend
          args: >
            -Dsonar.projectKey=prod-devsecops
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.qualitygate.wait=true

  blackduck:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Run npm audit for frontend
        working-directory: ./app/frontend
        run: npm audit

      - name: Run npm audit for backend
        working-directory: ./app/backend
        run: npm audit
  #    - uses: actions/checkout@v4
  #    - name: Black Duck Scan
  #      uses: synopsys-sig/github-action@v1
  #      with:
  #        blackduck_url: ${{ secrets.BLACKDUCK_URL }}
  #        blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    env:
      AWS_REGION: ap-south-1
      CLUSTER_NAME: devsecops-cluster
      ECR_REPOSITORY_BACKEND: backend
      ECR_REPOSITORY_FRONTEND: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: aws ecr get-login-password --region $AWS_REGION | \
             docker login --username AWS --password-stdin \
             ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build backend image
        run: |
          docker build -t $ECR_REPOSITORY_BACKEND:latest ./docker/backend
          docker tag $ECR_REPOSITORY_BACKEND:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_BACKEND:latest

      - name: Build frontend image
        run: |
          docker build -t $ECR_REPOSITORY_FRONTEND:latest ./docker/frontend
          docker tag $ECR_REPOSITORY_FRONTEND:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_FRONTEND:latest

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_BACKEND:latest
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Push images
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/backend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest

  gitops-update:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: harish4bvk/gitops-repo
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Update Helm values
        run: |
          sed -i "s/tag:.*/tag: latest/" helm/3tier-app/values.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image tags"
          git push
